AY2425S1-CS2103T-W14-1/tp

docs/AboutUs.md
=> Update AboutUs.md with Pravein's info

docs/AboutUs.md
=> Add Jian Yi about us details

docs/DeveloperGuide.md
=> Update value proposition in Developer's guide

docs/DeveloperGuide.md
=> update developer guide use cases

src/main/java/seedu/address/model/delivery/Delivery.java, src/main/java/seedu/address/model/delivery/DeliveryDetail.java, src/main/java/seedu/address/model/delivery/DeliveryStatus.java, src/main/java/seedu/address/model/delivery/DeliveryTime.java
=> Delivery feature increament

src/main/java/seedu/address/model/product/Product.java
=> Create Product class

src/main/java/seedu/address/model/person/Company.java
created a company class to represent a company object
=> create Company class

src/main/java/seedu/address/logic/commands/DeleteDeliveryCommand.java
=> Add DeleteDelivery Command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteDeliveryCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteDeliveryCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteDeliveryCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteDeliveryCommandParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/testutil/TypicalIndexes.java
=> Delete delivery command

src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/MarkDeliveryCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/delivery/Delivery.java, src/main/java/seedu/address/model/delivery/UniqueDeliveryList.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/MarkDeliveryCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/MarkDeliveryCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
=> Mark delivery command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/product/Product.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/storage/JsonAdaptedProduct.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
=> Add company product field

src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/Extensions.css, src/main/resources/view/PersonListCard.fxml
fixes #66 #63 
Update PersonListCard.fxml to display list of persons 
Update CSS files to improve UI
Change prefix for AddDeliveryCommand to standardise with rest of the commands
Rectify example for add delivery command
=> Edit UI to display person with new fields

src/main/java/seedu/address/logic/parser/CliSyntax.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/testutil/PersonUtil.java
=> Remove supplier status prefix

src/test/java/seedu/address/model/delivery/SupplierIndexTest.java
fixes #59 
Delivery test cases still pending discussion on use of multiple constructor
=> Add JUnit tests for SupplierIndex class

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/UpcomingCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/UpcomingCommandParser.java, src/main/java/seedu/address/model/delivery/DateTime.java, src/main/java/seedu/address/model/delivery/DateTimeBeforeInputDatePredicate.java, src/main/java/seedu/address/model/delivery/Delivery.java, src/main/java/seedu/address/model/delivery/DeliveryIsUpcomingPredicate.java, src/main/java/seedu/address/model/delivery/DeliveryStatusMatchInputPredicate.java, src/main/java/seedu/address/storage/JsonAdaptedDelivery.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/UpcomingCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/UpcomingCommandParserTest.java, src/test/java/seedu/address/model/delivery/DateTimeBeforeInputDatePredicateTest.java, src/test/java/seedu/address/model/delivery/DateTimeTest.java, src/test/java/seedu/address/model/delivery/DeliveryIsUpcomingPredicateTest.java, src/test/java/seedu/address/model/delivery/DeliveryStatusMatchInputPredicateTest.java, src/test/java/seedu/address/model/delivery/DeliveryTest.java, src/test/java/seedu/address/storage/JsonAdaptedDeliveryTest.java, src/test/java/seedu/address/testutil/DeliveryBuilder.java, src/test/java/seedu/address/testutil/TypicalDeliveries.java
Implement Upcoming command feature "upcoming dd-mm-yyyy hh:mm" to display all pending deliveries  in addressbook that will be completed before specified date. Delivery class currently still has a SupplierIndex field/
Write test cases for 
- UpcomingCommand
- UpcomingCommandParser
- DeliveryIsUpcomingPredicate
- DeliveryStatusMatchInputPredicate
- DateTimeBeforeInputDatePredicate
- Delivery
- DateTime
- AddressBookParser
fixes #90 #87
=> Upcoming Command feature

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java
Update user guide to show new command parameters, expected output and warnings
Edit AddDeliveryCommand MESSAGE_USAGE to remove spacing between prefix and corresponding value
fixes #110
=> Update User guide for add command

docs/UserGuide.md
=> Update UserGuide with Mark and Delete commands for deliveries

docs/diagrams/BetterModelClassDiagram.puml
Include new classes added to Delivery
Remove UniqueTagList association 
closes #117
=> Update UML class diagram for Model 

docs/diagrams/BetterModelClassDiagram.puml
Update model class diagram to include company, products and status to the supplier class
Closes #119
=> Update model class diagram supplier fields

docs/diagrams/UiClassDiagram.puml, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/ListAllCommand.java, src/main/java/seedu/address/logic/commands/ListDeliveryCommand.java, src/main/java/seedu/address/logic/commands/ListSupplierCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/ListAllCommandTest.java, src/test/java/seedu/address/logic/commands/ListSupplierCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Added seperate functionality to reset the lists
=> Update List Command

src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java, src/main/java/seedu/address/logic/parser/AddDeliveryCommandParser.java, src/main/java/seedu/address/model/delivery/Delivery.java, src/main/java/seedu/address/model/delivery/DeliveryWrapper.java, src/test/java/seedu/address/logic/commands/AddDeliveryCommandTest.java, src/test/java/seedu/address/logic/parser/AddDeliveryCommandParserTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/delivery/DeliveryWrapperTest.java, src/test/java/seedu/address/storage/JsonAdaptedDeliveryTest.java, src/test/java/seedu/address/testutil/DeliveryBuilder.java, src/test/java/seedu/address/testutil/DeliveryUtil.java, src/test/java/seedu/address/testutil/TypicalDeliveries.java, src/test/java/seedu/address/testutil/TypicalDeliveryWrappers.java
fixes #67 
Use wrapper class to wrap delivery object with supplier index
Remove supplier index field from Delivery class
=> Delivery class constructor 

src/main/java/seedu/address/logic/commands/AddDeliveryCommand.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/commands/DeleteDeliveryCommand.java, src/main/java/seedu/address/logic/commands/DeleteSupplierCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java, src/main/java/seedu/address/logic/commands/MarkSupplierCommand.java, src/test/java/seedu/address/logic/commands/AddDeliveryCommandTest.java
Fixes #132 
Fixes #134
Fixes #143 
Fixes #144 
Fixes #152 
Fixes #157 
Fixes #158 
Fixes #160
=> FIx delete and mark commands failing after sorting

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java, src/main/java/seedu/address/logic/commands/MarkDeliveryCommand.java, src/test/java/seedu/address/logic/commands/MarkDeliveryCommandTest.java
Fixes #138
Fixes #139
Fixes #140
=> Fix bugs in FindDeliveryCommand and MarkDeliveryCommand

src/main/java/seedu/address/model/delivery/DeliveryProductPredicate.java, src/main/java/seedu/address/model/delivery/DeliverySupplierPredicate.java, src/main/java/seedu/address/model/supplier/Supplier.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/supplier/SupplierTest.java, src/test/java/seedu/address/model/supplier/UniqueSupplierListTest.java
=> Update logic for same supplier

src/main/java/seedu/address/model/delivery/DeliverySortStatusComparator.java
Edit delivery status comparator to not sort by date and time within each status type
=> Edit delivery status comparator

src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java
=> Fix bug in FindDelivery command after sorting suppliers

src/main/resources/view/DeliveryListCard.fxml, src/main/resources/view/SupplierListCard.fxml
=> Set prefHeight for SupplierListCard and DeliveryListCard

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/UpcomingCommand.java
fixes #181 
Update parameters to include prefix for upcoming and AddDeliveryCommand in user guide
Reordered upcoming command message usage
=> Update upcoming command message

docs/UserGuide.md, src/main/java/seedu/address/logic/parser/MarkDeliveryCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java
=> Update Mark, Delete and Find Delivery commands in UserGuide

docs/DeveloperGuide.md, docs/diagrams/ArchitectureSequenceDiagramMarkSupplier.puml, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FindDeliveryCommand.java, src/test/java/seedu/address/logic/commands/FindDeliveryCommandTest.java
=> Update Architecture sequence diagram and NFRs in DG

docs/DeveloperGuide.md
=> Update user stories to developer guide

docs/DeveloperGuide.md
=> Update logic component in developer guide

src/main/java/seedu/address/model/delivery/Cost.java
=> Show duplicate delivery message if cost value is the same

docs/UserGuide.md, src/main/java/seedu/address/model/UserPrefs.java, src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json, src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
=> Update data json file name 

docs/DeveloperGuide.md, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/java/seedu/address/model/util/SampleDataUtilTest.java
=> Add sample deliveries

docs/UserGuide.md, src/main/java/seedu/address/MainApp.java
=> Edit supplier add list delete commands in ug

docs/diagrams/ModelClassDiagram.puml
=> Update model class diagram to be less cluttered

docs/DeveloperGuide.md
=> Remove BetterModelClassDiagram from DG

docs/UserGuide.md, docs/_markbind/layouts/default.md
Do help to check if the key features are valid
=> Fix broken links and added short summary of key features to the UG

docs/UserGuide.md
Do help to check that all the commands in the command summary are valid and all the links work
=> Update Command Summary Table in UG

docs/DeveloperGuide.md
=> Update DG for line spacing inconsistency

docs/UserGuide.md
=> Update Known Issues in UG

src/main/java/seedu/address/model/delivery/Cost.java, src/main/java/seedu/address/model/delivery/DateTime.java, src/main/java/seedu/address/model/delivery/DeliverySortBy.java, src/main/java/seedu/address/model/delivery/DeliverySortCostComparator.java, src/main/java/seedu/address/model/delivery/DeliverySortDateTimeComparator.java
=> Refactor delivery comparator compare method

docs/DeveloperGuide.md
=> Edit model description in DG
